* Слайд 1
  Защищается студент 236группы Кевролетин Василий Владимироваич. 
  Тема курсовой работы: "Доработка системы генераций тестовых заданий ЕГЭ по информатике".
  Руководитель: "Кленин Александр Сергеевич"
  
* Слайд 2
  Начну с определения некоторых терминов:
  
  Единый государственный экзамен – одна из форм государственной итоговой аттестации выпускников 11-х классов и вступительных испытаний в высшие и средние специальные учебные заведения. Проводится в форме тестирования.
  
  Вариант заданий - это набор сходных по структуре заданий, направленных на проверку одного и того же знания или навыка, отличающихся друг от друга формулировкой вопроса, или вариантами ответов. 
  
  Генерация задания - создание тестового задания при помощи генератора случайных чисел. 
  
  Генератор — процедура на языке программирования, генерирующая схожие по структуре задания на основе случайных алгоритмов.
  
* Слайд 3
  
  Для подготовки школьников к сдаче ЕГЭ по информатике требуется большое количество вариантов заданий. Для удволетворения существующей потребности в заданиях ЕГЭ по информатике А.С. Клениным была создана система автоматической генерации тестовых заданий.
  Цель моей курсовой работы: доработать данную систему.
  
* Слайд 4
  
  Выполнение работы началось с изучения уже существующих решений. Оказалось, что аналогичной системы автоматической генерации заданий ЕГЭ не существует, так что я отдельно привожу 2 сравнительные таблицы:
  -сравнение источников заданий ЕГЭ по информатике, которая сейчас перед вами.
  
* Слайд 5
  -и сравнение систем автоматической генерации заданий.
  
  Анализ источников заданий ЕГЭ по информатике подтвердил нехватку вариантов тестовых заданий. 
Анализ автоматических систем генерации тестовых заданий подтвердил отсутствие каких либо решений для автоматизированного создания заданий ЕГЭ.
  Таким образом востребованность системы генерации тестовых заданий ЕГЭ очевидна.
  
* Слайд 6
  
  Существующая система полностью написана на языке программирования perl с использованием системы контроля версий git. Так что перед началом работы мне было необходимо изучить данные инструменты разработки.
  Кроме того необходимо было изучить саму систему генерации тестовых заданий. Далее необходимо было изучить доступные официальные источники тестовых заданий ЕГЭ по информатике и выбрать задание, которые необходимо добавить в систему.
  После этого, начиная с простых и заканчивая сложными, добавить генераторы новых тестовых заданий.
  
* Слайд 7
  
  Мною было создано 8 генераторов заданий. 
* Появление рамки
  Из них я бы хотел рассмотреть подробнее 2, на мой взгляд, наиболее интересных генератора.
  
* Слайд 8
  
  Перед вами результат работы генератора B7. 
  В условии данной задачи говорится о том, что из 8 школьников 1 разбил окно. Каждый из ребят сделал высказывание утверждающее, что один из нескольких школьников виноват. Известно, что ровно 2 высказывания верны. Определить, кто виноват.
  
* Слайд 9
  
  Рассмотрим небольшой пример, в котором участвующих лиц зовут латинскими буквами "A" "B" "C" "D". Снизу приведены высказывания участников. 
  Допустим окно разбил ученик A. Тогда истино первое высказывание.
* Появление полосочки 
  
  Теперь если окно разбил ученик B истино 2 высказы
* Еще полосочка
  Аналогично проверим, какие высказывания истины, если выноват школьник C или D
* Полосочка
  
  Теперь рассмотрим другой пример
* Слайд 10
  
  ученик B говорит, что виноват либо B, либо С, поэтому его высказывание верно срузу на 2х вариатах ответа.
  
* Слайд 11
  
  Кроме диаграммы множеству высказываний можно сопоставить двоичную матрицу, каждая строка которой соответствует одному высказыванию.
  В рассмотренном мной оригинальном условии задачи все ученики сделали высказывание, причем не было высказываний всегда истиных или всегда ложных. 
* Появление замечаний
  Поэтому необходимо сгенерировать матрицу без пустых, и полностью заполненных строк. Кроме того, так как решение задачи должно быть единственным, необходимо, чтобы в матрице был столбец с уникальной степенью.
  
* Слайд 12
  
  Вместо того, чтобы сразу генерировать матрицу с заданными свойствами 
  создадим сначала матрицу без пустых и полностью заполненных строк.
  Затем, если в ней нет столбца с уникальноый степенью допишим новые пустые столбец и строку. 
* Слайд 13 - расширение матрицы
  В пустой строке расставим значений так, чтобы появился столбец с уникальной степенью. 
* Появление рамки
  При помощи полученной матрицы создадим высказывания учеников и условие задачи.
  
* Слайд 14
  
  Рассмотрим генератор задания B6.
  Условие задачи следующее:
  4 человека владеют каждый по одной профессии и живут в разных домах на
  одной улице.
  Даны ограничения нескольких типов, на расположения людей и профессий друг относительно друга.
  Требуется выяснить кто какой профессии и кто где живёт.
  
* Слайд 15
  
  Рассмотренная мной задача из официального источника заданий ЕГЭ 
  решалась следующим образом:
* Молния
  Сначала на основе ограничений выявлялся порядок расположения профессий
* Слайд 16 - Стрелочка
* Молния
  Затем учитываю уже известное расположение профессий и оставшиеся
  ограничения выяснялся порядок расположения людей.
* Слайд 17 - Стрелочка
  
  Соответственно, генерация задания так же  проходит в 2 похожих этапа:
  сначала генерируюся ограничения, задающие порядок расположения
  профессий. Затем, учитывая расположение профессий генерируются новые
  ограничения на расположение людей.
  
* Слайд 18
  
  Алгоритм генерации ограничений следующий:
  Начнём с пустого множества ограничений. При этом у нас имеется много
  способов расположить объекты.
* Ограничение 
  Случайным образом добавим огранечение. Если число вариантов
  расположить объекты уменьшилось запоминаем ограничение. Если бы число
  вариантов не уменьшилось или стало равным нулю, огранечение не следовало бы запоминать.
* Ограничения + рамка
  Продолжим процесс, пока не создадим ограничения, оставляющие один
  допустимый вариант расположения объектов.
  
  По созданным ограничениям сгенерируем условие задачи.
  
* Заключительный слайд
  
  Итак, я доработал существующий проект - систему генерации тестовых
  заданий ЕГЭ по информатике. 
  Разработанные мной генераторы заданий использовались в ходе проведения Весеннего
  турнира юних программистов для тестирования школьников. 
  Кроме того я преобрёл полезные навики программирования на языке perl и
  использования системы контроля версий git. 
  
  Спасибо за внимание.
  